export default {
	FETCH_TASKS_DATA: "FETCH_TASKS_DATA",
	SET_TASKS_DATA: "SET_TASKS_DATA",
	GET_TASKS: "GET_TASKS",
	SIGN_IN: "SIGN_IN",
	LOG_IN: "LOG_IN",
	SIGNING_IN: "SIGNING_IN",
	SAVE_TASK: "SAVE_TASK",
	TASK_SAVING: "TASK_SAVING",
};
